### ISSUE TITLE
[Epic] Gestion des réservations

### ISSUE THREAD

**Issue by Rachad-ng** [Rachad-ng/Demo_CI-CD#1]
Dans le projet , il faut assurer la gestion des réservations :
- Ajouter une réservation.
- Rechercher une réservation.
- Modifier une réservation.
- Supprimer une réservation.

Les taches à faire :
- [ ] Création des réservations.
- [ ] Recherche des réservations.
- [ ] Modification des réservations.
- [ ] Suppression des réservations #2
